export const HELLO_WORLD = 'HELLO_WORLD';
export const SEARCH_PROFILES_SUCCESS = 'SEARCH_PROFILES_SUCCESS'
export const SEARCH_PROFILES_ERROR = 'SEARCH_PROFILES_ERROR'
export const SET_PROFILE_HIDDEN = 'SET_PROFILE_HIDDEN'

export const GET_ESCORT_OF_THE_DAY_SUCCESS = 'GET_ESCORT_OF_THE_DAY_SUCCESS'
export const GET_ESCORT_OF_THE_DAY_ERROR = 'GET_ESCORT_OF_THE_DAY_ERROR'
export const GET_DIRECTCAM_OF_THE_DAY_SUCCESS = 'GET_DIRECTCAM_OF_THE_DAY_SUCCESS'
export const GET_DIRECTCAM_OF_THE_DAY_ERROR = 'GET_DIRECTCAM_OF_THE_DAY_ERROR'
export const GET_PHONECHAT_OF_THE_DAY_SUCCESS = 'GET_PHONECHAT_OF_THE_DAY_SUCCESS'
export const GET_PHONECHAT_OF_THE_DAY_ERROR = 'GET_PHONECHAT_OF_THE_DAY_ERROR'
export const GET_GROUP_OF_THE_DAY_SUCCESS = 'GET_GROUP_OF_THE_DAY_SUCCESS'
export const GET_GROUP_OF_THE_DAY_ERROR = 'GET_GROUP_OF_THE_DAY_ERROR'

export const TOGGLE_LIST_VISIBILITY = 'TOGGLE_LIST_VISIBILITY';
export const SET_SEARCH_FIELD_SELECTED_ITEM = 'SET_SEARCH_FIELD_SELECTED_ITEM';
export const SET_SEARCH_QUERY_SELECTED_ITEM = 'SET_SEARCH_QUERY_SELECTED_ITEM';

export const AWAPI_GETGENDERS_SUCCESS = 'AWAPI_GETGENDERS_SUCCESS';
export const AWAPI_GETGENDERS_ERROR = 'AWAPI_GETGENDERS_ERROR';
export const AWAPI_GETORIENTATIONS_SUCCESS = 'AWAPI_GETORIENTATIONS_SUCCESS';
export const AWAPI_GETORIENTATIONS_ERROR = 'AWAPI_GETORIENTATIONS_ERROR';

export const TOGGLE_SUBNAVSEARCH_VISIBILITY = 'TOGGLE_SUBNAVSEARCH_VISIBILITY';

export const SEARCHBAR_GENDER_SELECTED = 'SEARCHBAR_GENDER_SELECTED';
export const SEARCHBAR_SERVICE_SELECTED ='SEARCHBAR_SERVICE_SELECTED';
export const SEARCHBAR_ORIENTAION_SELECTED ='SEARCHBAR_ORIENTAION_SELECTED';
